// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults

values: {
	// Azure Subscription ID where resources will be created
	subscriptionId: string

	// Azure Region
	location: string | *"eastus"

	// Resource Naming
	names: {
		aksResourceGroup:     string
		networkResourceGroup: string
		aksCluster:           string
		vnet:                 string | *"\(aksCluster)-vnet"
	}

	// Tags to apply to all resources
	tags: { [string]: string } | *{}

	// Network Configuration
	network: {
		// The CIDR for the VNet
		cidr: string | *"10.100.0.0/16"
		// The Subnet for the AKS Nodes
		subnetCidr: string | *"10.100.0.0/24"
		// The CIDR for Pods (Overlay)
		podCidr: string | *"10.244.0.0/16"
		// The CIDR for Services
		serviceCidr: string | *"10.245.0.0/16"
		// The IP for DNS Service
		dnsServiceIP: string | *"10.245.0.10"
	}

	// Peering Configuration
	peering: {
		enabled: bool | *false
		remoteVnetId: string | *""
		remoteVnetName: string | *""
	}

	// Cluster Configuration
	cluster: {
		kubernetesVersion: string | *"1.29.0"
		dnsPrefix:         string | *names.aksCluster
		sku: {
			name: "Base"
			tier: "Standard"
		}
	}

	// Default Node Pool Configuration
	defaultNodePool: {
		name:    string | *"systempool"
		vmSize:  string | *"Standard_DS2_v2"
		count:   int | *2
		minCount: int | *1
		maxCount: int | *5
		mode:    "System"
	}
}

