// Timoni Bundle for {{OB_PROJECT_NAME}}
// Generated by ops-box self-service wizard

runtime: {
  name: string
}

global: {
  image: {
    tag: *"latest" | string
  }
}

bundle: {
  apiVersion: "v1alpha1"
  name:       "{{OB_PROJECT_NAME}}"
  instances: {
    "{{OB_PROJECT_NAME}}-{{SERVICE_NAME}}": {
      module: {
        url:     "oci://catalina.azurecr.io/classic-deployment"
        version: "0.2.3"
      }
      namespace: "{{OB_PROJECT_NAME}}-\(runtime.name)"
      values: {
        image: {
          repository: "catalina.azurecr.io/{{OB_PROJECT_NAME}}/{{SERVICE_NAME}}"
          tag:        global.image.tag
          digest:     ""
          pullPolicy: "IfNotPresent"
        }
        
        // Environment-specific replicas
        replicas: *1 | int
        if runtime.name == "prd" {
          replicas: 2
        }
        
        service: port: 3000
        containerPort: 3000
        probes: {
          liveness: {
            path: "/health"
            initialDelaySeconds: 30
            periodSeconds: 10
          }
          readiness: {
            path: "/health"
            initialDelaySeconds: 5
            periodSeconds: 5
          }
        }
        env: {
          NODE_ENV: "production"
          LOG_LEVEL: "INFO"
        }
        
        // Environment-specific resources
        resources: {
          if runtime.name == "prd" {
            requests: {
              cpu:    "200m"
              memory: "256Mi"
            }
            limits: {
              cpu:    "1000m"
              memory: "1Gi"
            }
          }
          if runtime.name != "prd" {
            requests: {
              cpu:    "100m"
              memory: "128Mi"
            }
            limits: {
              cpu:    "500m"
              memory: "512Mi"
            }
          }
        }
        
        // Environment-specific ingress
        ingress: {
          enabled: {{INGRESS_ENABLED}} // replaced with true or false by Vela workflow
          annotations: {
            "kubernetes.io/ingress.class": "nginx"
          }
          hosts: [
            {
              if runtime.name == "prd" {
                host: "{{OB_PROJECT_NAME}}.catmktg.com"
              }
              if runtime.name != "prd" {
                host: "{{OB_PROJECT_NAME}}-\(runtime.name).catmktg.com"
              }
              paths: [
                {
                  path:     "/"
                  pathType: "Prefix"
                },
              ]
            },
          ]
        }
      }
    }
  }
}
