---
# Instance: vm-test
---
apiVersion: compute.azure.com/v1api20220301
kind: VirtualMachine
metadata:
  annotations:
    serviceoperator.azure.com/credential-from: azureserviceoperator-system/aso-credential-catalina-vault-sqa
  name: vm-timoni-test-01
  namespace: default
spec:
  azureName: vm-timoni-test-01
  hardwareProfile:
    vmSize: Standard_B2s
  location: eastus
  networkProfile:
    networkInterfaces:
    - reference:
        name: vm-timoni-test-01-nic
  operatorSpec: {}
  osProfile:
    adminPassword:
      key: password
      name: vm-admin-password
    adminUsername: azureuser
    computerName: vm-timoni-test-01
    linuxConfiguration:
      disablePasswordAuthentication: false
  owner:
    name: rg-tst-eastus-istio-compute
  storageProfile:
    imageReference:
      offer: 0001-com-ubuntu-server-jammy
      publisher: Canonical
      sku: 22_04-lts-gen2
      version: latest
    osDisk:
      createOption: FromImage
      diskSizeGB: 30
      managedDisk:
        storageAccountType: Premium_LRS
  tags:
    Environment: test
    ManagedBy: timoni
    Project: timoni-poc
---
apiVersion: network.azure.com/v1api20240301
kind: NetworkInterface
metadata:
  annotations:
    serviceoperator.azure.com/credential-from: azureserviceoperator-system/aso-credential-catalina-vault-sqa
  name: vm-timoni-test-01-nic
  namespace: default
spec:
  azureName: vm-timoni-test-01-nic
  ipConfigurations:
  - name: ipconfig1
    subnet:
      reference:
        armId: /subscriptions/a50f971b-376d-4d05-ac33-1e9fcfb8f32c/resourceGroups/rg-np-eastus-dashboard/providers/Microsoft.Network/virtualNetworks/vn-np-eastus-10-166-54-0-24/subnets/sn-tst-eastus-istio-10-166-54-0-26-aks-b
  location: eastus
  operatorSpec: {}
  owner:
    name: rg-tst-eastus-istio-compute
  tags:
    Environment: test
    ManagedBy: timoni
    Project: timoni-poc
