apiVersion: ops-box.io/v1
kind: OBRole
metadata:
  name: admin
  namespace: ops-box
spec:
  description: Admin role with full permissions
  permissions:
    - allowed: true
      feature: admin_panel
      target: all
    - allowed: true
      feature: api_access
      target: all
    - allowed: true
      feature: view_rbac_definitions
      target: all
    - allowed: true
      feature: edit_rbac_definitions
      target: all
    - allowed: true
      feature: delete_rbac_definitions
      target: all
    - allowed: true
      feature: view_env_definitions
      target: all
    - allowed: true
      feature: edit_env_definitions
      target: all
    - allowed: true
      feature: delete_env_definitions
      target: all
    - allowed: true
      feature: view_cron_definitions
      target: all
    - allowed: true
      feature: edit_cron_definitions
      target: all
    - allowed: true
      feature: delete_cron_definitions
      target: all
    - allowed: true
      feature: view_git_definitions
      target: all
    - allowed: true
      feature: edit_git_definitions
      target: all
    - allowed: true
      feature: delete_git_definitions
      target: all
    - allowed: true
      feature: view_ado_definitions
      target: all
    - allowed: true
      feature: edit_ado_definitions
      target: all
    - allowed: true
      feature: delete_ado_definitions
      target: all
    - allowed: true
      feature: view_remote_clusters
      target: all
    - allowed: true
      feature: manage_remote_clusters
      target: all
    - allowed: true
      feature: manage_subjects
      target: all
    - allowed: true
      feature: manage_roles
      target: all
    - allowed: true
      feature: view_internal_rbac
      target: all
    - allowed: true
      feature: view_events
      target: all
    - allowed: true
      feature: manage_events
      target: all
    # Self-service portal
    - allowed: true
      feature: view_self_service
      target: all
    - allowed: true
      feature: edit_self_service
      target: all
    # Application project permissions
    - allowed: true
      feature: create_application_projects
      target: all
    - allowed: true
      feature: view_application_projects
      target: all
    - allowed: true
      feature: view_all_application_projects
      target: all
    - allowed: true
      feature: edit_application_projects
      target: all
    - allowed: true
      feature: edit_all_application_projects
      target: all
    - allowed: true
      feature: delete_application_projects
      target: all
    - allowed: true
      feature: delete_all_application_projects
      target: all
    # Template permissions
    - allowed: true
      feature: view_templates
      target: all
    - allowed: true
      feature: create_templates
      target: all
    # Infrastructure project permissions
    - allowed: true
      feature: view_infrastructure_projects
      target: all
    - allowed: true
      feature: view_all_infrastructure_projects
      target: all
    - allowed: true
      feature: create_infrastructure_project
      target: all
    - allowed: true
      feature: edit_infrastructure_project
      target: all
    - allowed: true
      feature: edit_all_infrastructure_projects
      target: all
    - allowed: true
      feature: delete_infrastructure_project
      target: all
    - allowed: true
      feature: delete_all_infrastructure_projects
      target: all
    - allowed: true
      feature: view_infrastructure_environments
      target: all
    # Infrastructure approvals
    - allowed: true
      feature: view_infrastructure_approvals
      target: all
    - allowed: true
      feature: approve_infrastructure_request
      target: all
    - allowed: true
      feature: reject_infrastructure_request
      target: all
    # IAC Manager
    - allowed: true
      feature: view_infrastructure_destinations
      target: all
    - allowed: true
      feature: edit_infrastructure_destinations
      target: all
    - allowed: true
      feature: delete_infrastructure_destinations
      target: all
    - allowed: true
      feature: commit_infrastructure_configs
      target: all
