apiVersion: ops-box.io/v1
kind: OBRole
metadata:
  name: gitops-developer
  namespace: ops-box
spec:
  description: "Developer role created via GitOps"
  permissions:
    - feature: view_rbac_definitions
      target: all
      allowed: true
    - feature: edit_rbac_definitions
      target: own
      allowed: true
    - feature: view_env_definitions
      target: all
      allowed: true
    - feature: edit_env_definitions
      target: own
      allowed: true
