apiVersion: ops-box.io/v1
kind: AdoPipelineDefinition
metadata:
  name: sample-api-pipeline
  namespace: ops-box
spec:
  # Draft mode - set to false to enable export
  draft: true
  
  # Source repository configuration
  sourceRepository:
    url: "https://github.com/example/sample-api"
    branch: "main"
  
  # Templates source configuration
  templatesSource:
    gitDefinitionName: "shared-pipeline-templates"
    basePath: "azure-pipelines"
  
  # Pipeline definition (Azure Pipelines YAML structure)
  pipelineDefinition:
    name: "SampleAPI-CI"
    pool:
      vmImage: "ubuntu-latest"
    trigger:
      branches:
        include:
          - main
          - develop
    stages:
      - stage: "Build"
        displayName: "Build Stage"
        jobs:
          - job: "BuildJob"
            displayName: "Build Application"
            steps:
              - task: "Bash@3"
                displayName: "Build .NET Application"
                inputs:
                  targetType: "inline"
                  script: |
                    echo "Building application..."
                    dotnet restore
                    dotnet build --configuration Release
              - task: "Bash@3"
                displayName: "Run Unit Tests"
                inputs:
                  targetType: "inline"
                  script: |
                    echo "Running tests..."
                    dotnet test --configuration Release --no-build
  
  # CD Configuration (optional deployment profiles)
  cdConfig:
    profiles:
      - name: "dev"
        environment: "dev"
        targetCluster: "aks-dev-eastus"
        namespace: "sample-api-dev"
        approvalRequired: false
      
      - name: "staging"
        environment: "staging"
        targetCluster: "aks-np-eastus"
        namespace: "sample-api-staging"
        approvalRequired: true
      
      - name: "production"
        environment: "production"
        targetCluster: "aks-prd-eastus2"
        namespace: "sample-api"
        approvalRequired: true
  
  # Output destinations for generated artifacts
  outputs:
    pipeline:
      gitDefinitionName: "source-code-repo"
      path: "devops/sample-api-pipeline.yml"
      branch: "test-k8s-ops-box-resources"
