apiVersion: v1
kind: ServiceAccount
metadata:
  name: vela-timoni-runner
  namespace: azureserviceoperator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: timoni-runner-role
rules:
  - apiGroups: ["resources.azure.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["containerservice.azure.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["network.azure.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["compute.azure.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "serviceaccounts", "namespaces"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: timoni-runner-binding
subjects:
  - kind: ServiceAccount
    name: vela-timoni-runner
    namespace: azureserviceoperator-system
roleRef:
  kind: ClusterRole
  name: timoni-runner-role
  apiGroup: rbac.authorization.k8s.io
