apiVersion: ops-box.io/v1
kind: CronDefinition
metadata:
  name: minikube-local-health-check
  namespace: ops-box
spec:
  jobType: python
  schedule: "*/10 * * * *" # Every 10 minutes (for testing)
  namespace: default
  pythonJob:
    image: python:3.11-slim
    script: |
      import datetime
      import sys
      import platform

      print("=== Python Health Check Job ===")
      print(f"Timestamp: {datetime.datetime.now()}")
      print(f"Python version: {sys.version}")
      print(f"Platform: {platform.platform()}")
      print("Health check: OK")
    requirements: |
      # No external dependencies for this simple health check
  jobConfig:
    successfulJobsHistoryLimit: 2
    failedJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    backoffLimit: 1
    activeDeadlineSeconds: 180
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "256Mi"
  reconciliation:
    selfHeal: true
    prune: true
