---
apiVersion: ops-box.io/v1
kind: GitDefinition
metadata:
  name: test-gitops-local
  namespace: ops-box
  annotations:
    description: "Self-syncing GitOps definition for k8s-ops-box resources"
spec:
  repository:
    url: "https://github.com/MaximKononenko/helm.git"
  branches:
    - name: test-k8s-ops-box-resources
      paths:
        # RemoteCluster definitions
        - path: "clusters/*.yaml"
          kind: RemoteCluster
        
        # Internal RBAC
        - path: "roles/*.yaml"
          kind: OBRole
        - path: "subjects/*.yaml"
          kind: OBSubject
        
        # RBACDefinition CRs for different clusters
        - path: "rbac-definitions/minikube-local-*.yaml"
          kind: RBACDefinition
          targetCluster: minikube-local
        - path: "rbac-definitions/dev-*.yaml"
          kind: RBACDefinition
          targetCluster: minikube-local
        - path: "rbac-definitions/staging-*.yaml"
          kind: RBACDefinition
          targetCluster: minikube-remote
        
        # CronDefinition CRs for different clusters
        - path: "cron-definitions/minikube-*.yaml"
          kind: CronDefinition
          targetCluster: minikube-local
        - path: "cron-definitions/dev-*.yaml"
          kind: CronDefinition
          targetCluster: dev-cluster-gitops
        - path: "cron-definitions/staging-*.yaml"
          kind: CronDefinition
          targetCluster: staging-cluster-gitops
        
        # GitDefinition CRs (self-sync bootstrap)
        - path: "git-definitions/*.yaml"
          kind: GitDefinition
  
  pollIntervalSeconds: 600  # 10 minutes
  
  syncPolicy:
    automated:
      prune: true      # Remove resources deleted from Git
      selfHeal: true   # Fix drift from manual changes
