// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults

values: {
	// Azure Subscription ID where resources will be created
	subscriptionId: string

	// Azure Region
	location: string | *"eastus"

	// Resource Naming
	names: {
		resourceGroup: string
		vm:            string
		networkInterface: string | *"\(vm)-nic"
		publicIP:         string | *"\(vm)-pip"
	}

	// Tags to apply to all resources
	tags: {[string]: string} | *{}

	// VM Configuration
	vm: {
		size:          string | *"Standard_B2s"
		adminUsername: string | *"azureuser"
		adminPasswordSecret: {
			name: string | *"vm-admin-password"
			key:  string | *"password"
		}
		osDiskSizeGB: int | *30
		imageReference: {
			publisher: string | *"Canonical"
			offer:     string | *"0001-com-ubuntu-server-jammy"
			sku:       string | *"22_04-lts-gen2"
			version:   string | *"latest"
		}
	}

	// Network Configuration (existing resources)
	network: {
		// Existing VNet resource group
		vnetResourceGroup: string
		// Existing VNet name
		vnetName: string
		// Existing Subnet name
		subnetName: string
	}

	// Public IP Configuration (disabled by default)
	publicIP: {
		enabled: bool | *false
		sku:     string | *"Standard"
	}

	// ASO2 Secret Reference for authentication
	credential: {
		name:      string | *"aso-credential-catalina-vault-sqa"
		namespace: string | *"azureserviceoperator-system"
	}
}
