# Timoni Bundle for {{PROJECT_NAME}}
# Generated by ops-box self-service wizard

bundle: {
  apiVersion: "v1alpha1"
  name:       "{{PROJECT_NAME}}"
  instances: {
    "{{PROJECT_NAME}}-{{SERVICE_NAME}}": {
      module: {
        url:     "oci://catalina.azurecr.io/classic-deployment"
        version: "0.2.3"
      }
      namespace: "{{PROJECT_NAME}}-dev"
      values: {
        image: {
          repository: "catalina.azurecr.io/{{PROJECT_NAME}}/{{SERVICE_NAME}}"
          tag:        string | *"latest"
          digest:     ""
          pullPolicy: "IfNotPresent"
        }
        replicas: 1
        service: port: {{PORT}}
        containerPort: {{PORT}}
        probes: {
          liveness: {
            path: "/health"
            initialDelaySeconds: 30
            periodSeconds: 10
          }
          readiness: {
            path: "/health"
            initialDelaySeconds: 5
            periodSeconds: 5
          }
        }
        env: {
          LOG_LEVEL: "INFO"
        }
        resources: {
          requests: {
            cpu:    "100m"
            memory: "128Mi"
          }
          limits: {
            cpu:    "500m"
            memory: "512Mi"
          }
        }
        ingress: {
          enabled: false
          annotations: {
            "kubernetes.io/ingress.class": "nginx"
          }
          hosts: [
            {
              host: "{{PROJECT_NAME}}-dev.catmktg.com"
              paths: [
                {
                  path:     "/"
                  pathType: "Prefix"
                },
              ]
            },
          ]
        }
      }
    }
  }
}
