apiVersion: ops-box.io/v1
kind: RBACDefinition
metadata:
  name: staging-rbac
  namespace: ops-box
spec:
  targetNamespace: "default"
  static: true
  deployedBy: "gitops-sync"
  # Custom roles for staging environment
  customRoles:
    - name: staging-deployer
      clusterScope: false
      targetNamespaces: ["default", "staging"]
      rules:
        - apiGroups: ["apps"]
          resources: ["deployments", "replicasets"]
          verbs: ["get", "list", "watch", "create", "update", "patch"]
        - apiGroups: [""]
          resources: ["pods", "services"]
          verbs: ["get", "list", "watch"]
  # RBAC bindings
  rbacBindings:
    - name: staging-team-bindings
      subjects:
        - kind: Group
          name: staging-team
      roleBindings:
        - role: staging-deployer
          targetNamespaces: ["default", "staging"]
