{{- if .Values.configmap.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api {
            proxy_pass http://{{ .Release.Name }}-backend:{{ .Values.global.backendPort | default 5000 }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
{{- end }}